### PR TITLE
feat: add typescript support

### PR DESCRIPTION
**Pull request by miichom**
This was requested within https://github.com/xivapi/xivapi-js/issues/15

- [x] Fix response data bugs be685cc583ec3343770dd873e5ea57e3e9f002bd
- [x] Seperate typings for typescript users to import 9ae32b4b5f6c808a32b21ea8d6123c2b3dace614
- [x] Final external project checks 856ccd9f339e67097f14e1b92bd8a5f9a6fd2252

### CODE REVIEW

**Comment by miichom** [comment]
If there was something I missed or added please let me know, I was following both what was included under the JSDocs and [xivapi.com/docs](https://xivapi.com/docs) 👍

**Comment by kaimoe** [comment]
Thanks for all the effort! Is this still a draft or good to go?

**Comment by miichom** [comment]
I have been testing it in my project, I will have a look other it tonight and mark it if it's completely up to date.

**Comment by miichom** [comment]
> Thanks for all the effort! Is this still a draft or good to go?

It is good to go now!

**Pull request merged**
